[web]
  title = "Simple Flash Cards App"
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = []
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
